### PR TITLE
fix(tests and events): resolves unsupported events and passing tests

### LINKED ISSUE #23: Can not test fireEvent.touchStart side effects
- `preact-testing-library` version: 1.0.2
- `preact` version: 10.3.2
- `node` version: 13.9.0
- `npm` (or `yarn`) version: 6.13.7

**Relevant code or config**
Button.js 
```
const Button = ({myHandler}) => (
    <button data-testid='my-button' onTouchStart={myHandler}>Click me</button>
)

export default Button;
```

Button.test.js
```
import { render, fireEvent } from '@testing-library/preact';
import Button from './Button';

describe('Button behavior test:', () => {
   it('Should call myHandler on touchStart', () => {
        const mockFn = jest.fn();
        const { getByTestId } = render(<Button myHandler={mockFn} />);
        fireEvent.touchStart(getByTestId('my-button'));
        expect(mockFn).toHaveBeenCalled();
   });
});
```

**What you did:**
Simple button component with onTouchStart event that triggers a prop method.

**What happened:**
I can not test it due to fireEvent.touchStart is not triggering the event and not creating side effects on my component.

Problem description:
I need to unit test the side effects of onTouchStart / onTouchEnd events on my components.

### LINKED ISSUE #51: touch events (onTouchEnter) do not work in jest jsdom
- `preact-testing-library` version: 2.0.1
- `preact` version: 10.7.0
- `node` version: 16.14.2
- `npm` (or `yarn`) version: yarn 1.22.17

**Relevant code or config**

https://github.com/rburgst/preact-testing-lib-pointer-events-bug

## Problem description:

The following does not work

```typescript
interface TestComponentProps {
    onPointerEnter: () => void
    onClick: () => void
}
export const TestComponent : FunctionComponent<TestComponentProps> = ({onPointerEnter, onClick}) => {
    return <div onPointerEnter={onPointerEnter} onClick={onClick} data-testid="test-div">My Div</div>
}
```

and the corresponding test
```typescript

interface TestComponentProps {
    onPointerEnter: () => void
    onClick: () => void
}
export const TestComponent : FunctionComponent<TestComponentProps> = ({onPointerEnter, onClick}) => {
    return <div onPointerEnter={onPointerEnter} onClick={onClick} data-testid="test-div">My Div</div>
}
```

The problem appears that the listeners in jsdom are registered with `PointerEnter` while the event being fired is `pointerenter`.

## Reproduction repository:

https://github.com/rburgst/preact-testing-lib-pointer-events-bug

## Suggested solution:

It looks to me as if the listeners in jsdom should be registered all lowercase.

### PR DESCRIPTION
**Pull request by mikerob215**
fixes #51
fixes #23

I updated the test suite to use names for event handlers in camel case like users do( ie: `onClick` was being tested as `onclick`). Once this is corrected,
a number of tests will fail as JSDOM doesnt have support for them. When a user writea a component with a prop like `onPointerEnter`, preact will do something like `'on' + eventName.toLowerCase() in elem` and in jsdom that wont work. It leads to preact creating an event handler called `PointerEnter` rather than `pointerEnter`.

To solve I've overridden `fireEvent` similar to how its done in RTL, the difference is that we make the same check as preact, `eventName.toLowerCase() in dom`,  to determine what the dispatch event's name should be.

Currently the PTL library typings indicate that this is supported and it also works fine in RTL.

First I fixed a test case then spent some time in a bugger to figure who was renaming the event names

**Checklist**:

- [N/A ] Documentation added
- [ X] Tests
- [ N/A] Typescript definitions updated
- [X ] Ready to be merged

### CODE REVIEW

File: src/__tests__/events.js [hunk 1]
```diff
@@ -169,9 +172,9 @@ test('onInput works', () => {
 test('calling `fireEvent` directly works too', () => {
```
Comment (JoviDeCroock) [inline src/__tests__/events.js:172]: Let's add a test specifically for the issue tagged here

File: src/file-event.js [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+Object.keys(domFireEvent).forEach((key) => {
+  fireEvent[key] = (elem) => {
+    // when preact sets up an event listener it uses this check
+    // `'on' + eventName.toLowerCase() in dom`,
+    // to determine eventName from prop and this works in browser, but in jsdom if an event
+    // isn't supported, preact's check will
+    // fail and lead it to dispatch an event like `PointerStart` instead of `pointerStart`
+
+    // Here we can duplicate the check in preact and case the way preact will
```
Comment (JoviDeCroock) [inline src/file-event.js:15]:
```suggestion
    // Preact registers event-listeners in lower-case, so onPointerStart becomes pointerStart
    // here we will copy this behavior, when we fire an element we will fire it in lowercase so we hit
    // the Preact listeners.
```

File: src/__tests__/events.js (hunk 1 above)
Comment (mikerob215) [reply src/__tests__/events.js:172]: I added those to the big list of tests, they should be covered, they were just missing before. With this bug they would have passing tests anyway.

File: src/pure.js [hunk 3]
```diff
@@ -1,6 +1,7 @@
 import { getQueriesForElement, prettyDOM, configure as configureDTL } from '@testing-library/dom'
 import { h, hydrate as preactHydrate, render as preactRender } from 'preact'
-import { act, setupRerender } from 'preact/test-utils'
+import { act } from 'preact/test-utils'
+import { fireEvent } from './file-event'
```
Comment (JoviDeCroock) [inline src/pure.js:4]:
```suggestion
import { fireEvent } from './fire-event'
```

File: src/__tests__/events.js (hunk 1 above)
Comment (mikerob215) [reply src/__tests__/events.js:172]: The other related issue, I think the bottom issue in open was about events that were already covered in this test suite too. All passed.

Comment (JoviDeCroock) [reply src/__tests__/events.js:172]: updated the description to link to the issue as that was missing

File: src/file-event.js [hunk 4]
```diff
@@ -0,0 +1,18 @@
+import { fireEvent as domFireEvent, createEvent } from '@testing-library/dom'
```
Comment (JoviDeCroock) [inline src/file-event.js:1]: this file is named incorrectly 😅

File: src/__tests__/events.js (hunk 1 above)
Comment (mikerob215) [reply src/__tests__/events.js:172]: Would it be worth adding reverse tests? I dont know if if thats a thing but we could write tests that check `'onpointerenter' in dom` and once they fail, we'd know we could delete these patches?

File: src/fire-event.js [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+// Similar to RTL we make are own fireEvent helper that just calls DTL's fireEvent with that
+// we can that any specific behaviors to the helpers we need
+export const fireEvent = (...args) => domFireEvent(...args)
+
+Object.keys(domFireEvent).forEach((key) => {
+  fireEvent[key] = (elem) => {
+    // Preact registers event-listeners in lower-case, so onPointerStart becomes pointerStart
+    // here we will copy this behavior, when we fire an element we will fire it in lowercase so
+    // wae hit the Preact listeners.
```
Comment (JoviDeCroock) [inline src/fire-event.js:11]:
```suggestion
    // we hit the Preact listeners.
```

**Review by JoviDeCroock — APPROVED** [review]

File: src/__tests__/events.js (hunk 1 above)
Comment (JoviDeCroock) [reply src/__tests__/events.js:172]: I would leave them out for now

Comment (mikerob215) [reply src/__tests__/events.js:172]: Worth adding them in another pr? Like I said, looking for ways to contribute

**Comment by mikerob215** [comment]
Thanks for the support @JoviDeCroock

**Comment by JoviDeCroock** [comment]
No worries should be published now @mikerob215 will focus on #50 now
